Deploy to CloudRun

diff --git a/.buildkite/deploy-production b/.buildkite/deploy-production
--- a/.buildkite/deploy-production
+++ b/.buildkite/deploy-production
@@ -13,23 +13,26 @@ manifest="$(mktemp)"
 echo '--- :kubernetes: Shipping'
 gcloud config set project banba-group
 gcloud container clusters get-credentials production --zone us-central1
-envsubst < k8s/production/deployment.yaml > "${manifest}"
-kubectl apply -f "${manifest}"
 
-echo '--- :zzz: Waiting for deployment'
+gcloud run deploy jonathanclarke-ie --image $DOCKER_IMAGE
 
-ATTEMPTS=0
-ROLLOUT_STATUS_CMD="kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie"
-until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 100 ]; do
-    $ROLLOUT_STATUS_CMD
-    ATTEMPTS=$((attempts + 1))
-    echo "."
-    sleep 10
-done
+# envsubst < k8s/production/deployment.yaml > "${manifest}"
+# kubectl apply -f "${manifest}"
 
-if ! kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie; then
-    echo "Failed to deploy; rolling back the deployment"
-    kubectl rollout undo deployment jonathanclarke-ie --namespace=jonathanclarke-ie
-    kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie
-    exit 1
-fi
+# echo '--- :zzz: Waiting for deployment'
+
+# ATTEMPTS=0
+# ROLLOUT_STATUS_CMD="kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie"
+# until $ROLLOUT_STATUS_CMD || [ $ATTEMPTS -eq 100 ]; do
+#     $ROLLOUT_STATUS_CMD
+#     ATTEMPTS=$((attempts + 1))
+#     echo "."
+#     sleep 10
+# done
+
+# if ! kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie; then
+#     echo "Failed to deploy; rolling back the deployment"
+#     kubectl rollout undo deployment jonathanclarke-ie --namespace=jonathanclarke-ie
+#     kubectl rollout status deployment jonathanclarke-ie --namespace=jonathanclarke-ie
+#     exit 1
+# fi
